// AUTO-GENERATED by scripts/generate-example-sources.mjs — do not edit by hand.
// Regenerate with: node scripts/generate-example-sources.mjs
import type { ResourceKind } from '../models/domain';

export interface ExampleSourceFile {
  readonly name: string;
  readonly path: string;
  readonly code: string;
}

export interface ExampleSourceSet {
  readonly label: string;
  readonly files: readonly ExampleSourceFile[];
}

export const EXAMPLE_SOURCES: Record<ResourceKind, ExampleSourceSet> = {
  posts: {
    label: 'Post',
    files: [
      {
        name: 'post.model.ts',
        path: 'models/post.model.ts',
        code: `/**
 * The \`Post\` domain model.
 *
 * ng-ql is not an ORM — this interface is a plain shape for the JSON your API
 * returns. There's no base class to extend and no decorators to apply; any
 * TypeScript interface works as a model for {@link PostResource}.
 */
export interface Post {
  id: number;
  title: string;
  status: 'draft' | 'published' | 'archived';
  categoryId: number;
  authorId: number;
  views: number;
  createdAt: string;
}`,
      },
      {
        name: 'post-resource.ts',
        path: 'resources/post-resource.ts',
        code: `import { Injectable } from '@angular/core';
import { NgQlClient, NgQlResource } from 'ng-ql';
import type { Post } from '../models/post.model';

/**
 * Typed ng-ql resource for the \`/posts\` endpoint.
 *
 * This is the entire integration: extend {@link NgQlResource}, pass it the
 * \`NgQlClient\` (injected like any other service) and an endpoint. Everything
 * else — building requests, caching, CRUD — comes from the base class.
 *
 * ### Observable API
 * \`\`\`ts
 * private readonly posts = inject(PostResource);
 *
 * this.posts
 *   .query()
 *   .where('status', 'published')
 *   .whereIn('categoryId', [1, 2])
 *   .with('author')
 *   .orderBy('createdAt', 'desc')
 *   .limit(10)
 *   .get()
 *   .subscribe((posts) => console.log(posts));
 *
 * this.posts.first().subscribe((post) => console.log(post)); // null if none
 * this.posts.find(42).subscribe((post) => console.log(post));
 * this.posts.query().paginate(1, 20).subscribe((page) => console.log(page.data, page.meta));
 * \`\`\`
 *
 * ### Signal API
 * \`\`\`ts
 * // Call from a field initializer, constructor, or runInInjectionContext(...).
 * protected readonly publishedPosts = this.posts
 *   .query()
 *   .where('status', 'published')
 *   .orderBy('createdAt', 'desc')
 *   .getSignal({ cache: 'stale-while-revalidate', cacheTtl: 30_000 });
 *
 * // In the template: publishedPosts.data() / .loading() / .error() / .status()
 * // publishedPosts.refresh() / publishedPosts.invalidate()
 *
 * protected readonly postsPage = this.posts.query().paginateSignal(1, 10);
 * // postsPage.data() / .meta() / .links() / .setPage(2) / .setPerPage(25)
 * \`\`\`
 *
 * ### CRUD (POST / PUT / PATCH / DELETE)
 * \`\`\`ts
 * this.posts.create({ title: 'New post', status: 'draft' }).subscribe();
 * this.posts.update(1, { title: 'Replaces the whole record' }).subscribe();
 * this.posts.patch(1, { status: 'published' }).subscribe();
 * this.posts.destroy(1).subscribe();
 * // Every one of these automatically invalidates cached \`posts\` reads.
 * \`\`\`
 */
@Injectable({ providedIn: 'root' })
export class PostResource extends NgQlResource<Post, number> {
  constructor(client: NgQlClient) {
    super(client, { endpoint: 'posts', cacheTags: ['posts'] });
  }
}`,
      },
      {
        name: 'post-manager.component.ts',
        path: 'examples/post-manager.component.ts',
        code: `import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import type { Post } from '../models/post.model';
import { PostResource } from '../resources/post-resource';

/**
 * A complete, real feature component built directly on ng-ql — not a
 * generic/dynamic viewer. This is what consuming \`PostResource\` in an
 * actual application looks like: a paginated Signal-backed list, a
 * create/edit form, and one-click PATCH/DELETE actions, all typed against
 * the plain {@link Post} model.
 */
@Component({
  selector: 'app-post-manager',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './post-manager.component.html',
  styleUrl: './post-manager.component.scss',
})
export class PostManagerComponent {
  private readonly posts = inject(PostResource);

  /** A live, cached, paginated Signal read — created once, right here. */
  protected readonly postsState = this.posts
    .query()
    .orderBy('createdAt', 'desc')
    .paginateSignal(1, 5);

  protected readonly formOpen = signal(false);
  protected readonly editingId = signal<number | null>(null);
  protected readonly saving = signal(false);
  protected form: Partial<Post> = this.emptyForm();

  private emptyForm(): Partial<Post> {
    return { title: '', status: 'draft', categoryId: 1, authorId: 1 };
  }

  startCreate(): void {
    this.editingId.set(null);
    this.form = this.emptyForm();
    this.formOpen.set(true);
  }

  startEdit(post: Post): void {
    this.editingId.set(post.id);
    this.form = {
      title: post.title,
      status: post.status,
      categoryId: post.categoryId,
      authorId: post.authorId,
    };
    this.formOpen.set(true);
  }

  cancel(): void {
    this.formOpen.set(false);
  }

  save(): void {
    const id = this.editingId();
    this.saving.set(true);
    const request = id === null ? this.posts.create(this.form) : this.posts.update(id, this.form);
    request.subscribe({
      next: () => {
        this.saving.set(false);
        this.formOpen.set(false);
        this.postsState.refresh();
      },
      error: () => this.saving.set(false),
    });
  }

  /** A one-click PATCH — a real partial update, not the full form. */
  publish(post: Post): void {
    this.posts.patch(post.id, { status: 'published' }).subscribe(() => this.postsState.refresh());
  }

  remove(id: number): void {
    this.posts.destroy(id).subscribe(() => this.postsState.refresh());
  }

  setPage(page: number): void {
    if (page < 1) return;
    this.postsState.setPage(page);
  }
}`,
      },
      {
        name: 'post-manager.component.html',
        path: 'examples/post-manager.component.html',
        code: `<div class="manager">
  <header class="manager__header">
    <div>
      <h3>Posts</h3>
      <p class="manager__hint">
        Live example — <code>PostResource</code> extends <code>NgQlResource&lt;Post&gt;</code>.
      </p>
    </div>
    <button type="button" class="btn btn--primary" (click)="startCreate()">+ New post</button>
  </header>

  @if (formOpen()) {
    <form class="manager__form" (ngSubmit)="save()">
      <label>
        Title
        <input
          name="title"
          type="text"
          [ngModel]="form.title"
          (ngModelChange)="form.title = $event"
          required
        />
      </label>
      <label>
        Status
        <select name="status" [ngModel]="form.status" (ngModelChange)="form.status = $event">
          <option value="draft">Draft</option>
          <option value="published">Published</option>
          <option value="archived">Archived</option>
        </select>
      </label>
      <label>
        Category ID
        <input
          name="categoryId"
          type="number"
          [ngModel]="form.categoryId"
          (ngModelChange)="form.categoryId = $event"
        />
      </label>
      <label>
        Author ID
        <input
          name="authorId"
          type="number"
          [ngModel]="form.authorId"
          (ngModelChange)="form.authorId = $event"
        />
      </label>
      <div class="manager__form-actions">
        <button type="submit" class="btn btn--primary" [disabled]="saving()">
          {{ editingId() === null ? 'Create post' : 'Save changes' }}
        </button>
        <button type="button" class="btn btn--ghost" (click)="cancel()">Cancel</button>
      </div>
    </form>
  }

  @if (postsState.error()) {
    <div class="error-banner">Something went wrong loading posts. Try again.</div>
  }

  @if (postsState.loading() && !postsState.hasData()) {
    <p class="hint">Loading posts…</p>
  } @else if (postsState.hasData() && postsState.data()!.length === 0) {
    <p class="hint hint--empty">No posts yet — create one above.</p>
  } @else if (postsState.hasData()) {
    <ul class="post-list">
      @for (post of postsState.data(); track post.id) {
        <li class="post-card">
          <div class="post-card__main">
            <span class="post-card__title">{{ post.title }}</span>
            <span class="status-chip" [class]="'status-chip--' + post.status">{{
              post.status
            }}</span>
          </div>
          <div class="post-card__meta">
            #{{ post.id }} · {{ post.views }} views · {{ post.createdAt | date: 'mediumDate' }}
          </div>
          <div class="post-card__actions">
            <button type="button" class="btn btn--ghost" (click)="startEdit(post)">Edit</button>
            <button
              type="button"
              class="btn btn--ghost"
              [disabled]="post.status === 'published'"
              (click)="publish(post)"
            >
              Publish
            </button>
            <button type="button" class="btn btn--danger" (click)="remove(post.id)">Delete</button>
          </div>
        </li>
      }
    </ul>

    @if (postsState.meta(); as meta) {
      <div class="pagination-bar">
        <button
          type="button"
          class="btn"
          [disabled]="meta.currentPage <= 1"
          (click)="setPage(meta.currentPage - 1)"
        >
          ← Prev
        </button>
        <span>Page {{ meta.currentPage }} of {{ meta.lastPage }}</span>
        <button
          type="button"
          class="btn"
          [disabled]="meta.currentPage >= (meta.lastPage ?? 1)"
          (click)="setPage(meta.currentPage + 1)"
        >
          Next →
        </button>
      </div>
    }
  }
</div>`,
      },
    ],
  },
  users: {
    label: 'User',
    files: [
      {
        name: 'user.model.ts',
        path: 'models/user.model.ts',
        code: `/** The \`User\` domain model. See {@link UserResource} for how it's queried. */
export interface User {
  id: number;
  name: string;
  email: string;
  role: 'admin' | 'editor' | 'viewer';
  active: boolean;
  createdAt: string;
}`,
      },
      {
        name: 'user-resource.ts',
        path: 'resources/user-resource.ts',
        code: `import { Injectable } from '@angular/core';
import { NgQlClient, NgQlResource } from 'ng-ql';
import type { User } from '../models/user.model';

/**
 * Typed ng-ql resource for the \`/users\` endpoint.
 *
 * \`\`\`ts
 * private readonly users = inject(UserResource);
 *
 * // Observable: filter, sort, paginate
 * this.users
 *   .query()
 *   .where('role', 'admin')
 *   .whereNotNull('email')
 *   .orderBy('name')
 *   .get()
 *   .subscribe((admins) => console.log(admins));
 *
 * // Signal: cache-first reads with manual refresh/invalidate
 * protected readonly activeUsers = this.users
 *   .query()
 *   .where('active', true)
 *   .getSignal({ cache: 'cache-first', cacheTtl: 60_000 });
 *
 * // CRUD
 * this.users.create({ name: 'Ada Lovelace', email: 'ada@example.com', role: 'editor', active: true });
 * this.users.patch(7, { active: false }).subscribe();
 * this.users.destroy(7).subscribe();
 * \`\`\`
 */
@Injectable({ providedIn: 'root' })
export class UserResource extends NgQlResource<User, number> {
  constructor(client: NgQlClient) {
    super(client, { endpoint: 'users', cacheTags: ['users'] });
  }
}`,
      },
      {
        name: 'user-manager.component.ts',
        path: 'examples/user-manager.component.ts',
        code: `import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import type { User } from '../models/user.model';
import { UserResource } from '../resources/user-resource';

/**
 * A real feature built on \`UserResource\` — a Signal-backed list plus a
 * create/edit form, and a one-click PATCH to toggle \`active\` without
 * opening the form at all.
 */
@Component({
  selector: 'app-user-manager',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './user-manager.component.html',
  styleUrl: './user-manager.component.scss',
})
export class UserManagerComponent {
  private readonly users = inject(UserResource);

  protected readonly usersState = this.users.query().orderBy('name').paginateSignal(1, 5);

  protected readonly formOpen = signal(false);
  protected readonly editingId = signal<number | null>(null);
  protected readonly saving = signal(false);
  protected form: Partial<User> = this.emptyForm();

  private emptyForm(): Partial<User> {
    return { name: '', email: '', role: 'viewer', active: true };
  }

  startCreate(): void {
    this.editingId.set(null);
    this.form = this.emptyForm();
    this.formOpen.set(true);
  }

  startEdit(user: User): void {
    this.editingId.set(user.id);
    this.form = { name: user.name, email: user.email, role: user.role, active: user.active };
    this.formOpen.set(true);
  }

  cancel(): void {
    this.formOpen.set(false);
  }

  save(): void {
    const id = this.editingId();
    this.saving.set(true);
    const request = id === null ? this.users.create(this.form) : this.users.update(id, this.form);
    request.subscribe({
      next: () => {
        this.saving.set(false);
        this.formOpen.set(false);
        this.usersState.refresh();
      },
      error: () => this.saving.set(false),
    });
  }

  toggleActive(user: User): void {
    this.users.patch(user.id, { active: !user.active }).subscribe(() => this.usersState.refresh());
  }

  remove(id: number): void {
    this.users.destroy(id).subscribe(() => this.usersState.refresh());
  }

  setPage(page: number): void {
    if (page < 1) return;
    this.usersState.setPage(page);
  }
}`,
      },
      {
        name: 'user-manager.component.html',
        path: 'examples/user-manager.component.html',
        code: `<div class="manager">
  <header class="manager__header">
    <div>
      <h3>Users</h3>
      <p class="manager__hint">
        Live example — <code>UserResource</code> extends <code>NgQlResource&lt;User&gt;</code>.
      </p>
    </div>
    <button type="button" class="btn btn--primary" (click)="startCreate()">+ New user</button>
  </header>

  @if (formOpen()) {
    <form class="manager__form" (ngSubmit)="save()">
      <label>
        Name
        <input
          name="name"
          type="text"
          [ngModel]="form.name"
          (ngModelChange)="form.name = $event"
          required
        />
      </label>
      <label>
        Email
        <input
          name="email"
          type="email"
          [ngModel]="form.email"
          (ngModelChange)="form.email = $event"
          required
        />
      </label>
      <label>
        Role
        <select name="role" [ngModel]="form.role" (ngModelChange)="form.role = $event">
          <option value="admin">Admin</option>
          <option value="editor">Editor</option>
          <option value="viewer">Viewer</option>
        </select>
      </label>
      <label class="manager__checkbox">
        <input
          name="active"
          type="checkbox"
          [ngModel]="form.active"
          (ngModelChange)="form.active = $event"
        />
        Active
      </label>
      <div class="manager__form-actions">
        <button type="submit" class="btn btn--primary" [disabled]="saving()">
          {{ editingId() === null ? 'Create user' : 'Save changes' }}
        </button>
        <button type="button" class="btn btn--ghost" (click)="cancel()">Cancel</button>
      </div>
    </form>
  }

  @if (usersState.error()) {
    <div class="error-banner">Something went wrong loading users. Try again.</div>
  }

  @if (usersState.loading() && !usersState.hasData()) {
    <p class="hint">Loading users…</p>
  } @else if (usersState.hasData() && usersState.data()!.length === 0) {
    <p class="hint hint--empty">No users yet — create one above.</p>
  } @else if (usersState.hasData()) {
    <ul class="user-list">
      @for (user of usersState.data(); track user.id) {
        <li class="user-row">
          <div class="user-row__identity">
            <span class="user-row__name">{{ user.name }}</span>
            <span class="user-row__email">{{ user.email }}</span>
          </div>
          <span class="role-chip" [class]="'role-chip--' + user.role">{{ user.role }}</span>
          <button
            type="button"
            class="active-toggle"
            [class.active-toggle--on]="user.active"
            (click)="toggleActive(user)"
          >
            {{ user.active ? 'Active' : 'Inactive' }}
          </button>
          <div class="user-row__actions">
            <button type="button" class="btn btn--ghost" (click)="startEdit(user)">Edit</button>
            <button type="button" class="btn btn--danger" (click)="remove(user.id)">Delete</button>
          </div>
        </li>
      }
    </ul>

    @if (usersState.meta(); as meta) {
      <div class="pagination-bar">
        <button
          type="button"
          class="btn"
          [disabled]="meta.currentPage <= 1"
          (click)="setPage(meta.currentPage - 1)"
        >
          ← Prev
        </button>
        <span>Page {{ meta.currentPage }} of {{ meta.lastPage }}</span>
        <button
          type="button"
          class="btn"
          [disabled]="meta.currentPage >= (meta.lastPage ?? 1)"
          (click)="setPage(meta.currentPage + 1)"
        >
          Next →
        </button>
      </div>
    }
  }
</div>`,
      },
    ],
  },
  products: {
    label: 'Product',
    files: [
      {
        name: 'product.model.ts',
        path: 'models/product.model.ts',
        code: `/** The \`Product\` domain model. See {@link ProductResource} for how it's queried. */
export interface Product {
  id: number;
  name: string;
  category: string;
  price: number;
  stock: number;
  featured: boolean;
  createdAt: string;
}`,
      },
      {
        name: 'product-resource.ts',
        path: 'resources/product-resource.ts',
        code: `import { Injectable } from '@angular/core';
import { NgQlClient, NgQlResource } from 'ng-ql';
import type { Product } from '../models/product.model';

/**
 * Typed ng-ql resource for the \`/products\` endpoint.
 *
 * \`\`\`ts
 * private readonly products = inject(ProductResource);
 *
 * // Observable: range filter + field selection
 * this.products
 *   .query()
 *   .whereBetween('price', [10, 50])
 *   .select(['id', 'name', 'price'])
 *   .get()
 *   .subscribe((cheapProducts) => console.log(cheapProducts));
 *
 * // Signal: paginated, network-first (falls back to cache if the request fails)
 * protected readonly catalog = this.products
 *   .query()
 *   .orderBy('name')
 *   .paginateSignal(1, 24, { cache: 'network-first' });
 *
 * // CRUD
 * this.products.create({ name: 'Widget', category: 'Home', price: 19.99, stock: 100, featured: false });
 * this.products.update(3, { name: 'Widget Pro', category: 'Home', price: 24.99, stock: 80, featured: true });
 * this.products.destroy(3).subscribe();
 * \`\`\`
 */
@Injectable({ providedIn: 'root' })
export class ProductResource extends NgQlResource<Product, number> {
  constructor(client: NgQlClient) {
    super(client, { endpoint: 'products', cacheTags: ['products'] });
  }
}`,
      },
      {
        name: 'product-manager.component.ts',
        path: 'examples/product-manager.component.ts',
        code: `import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import type { Product } from '../models/product.model';
import { ProductResource } from '../resources/product-resource';

/**
 * A real feature built on \`ProductResource\` — a Signal-backed, sorted,
 * paginated list, a create/edit form, and a one-click PATCH to toggle
 * \`featured\`.
 */
@Component({
  selector: 'app-product-manager',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './product-manager.component.html',
  styleUrl: './product-manager.component.scss',
})
export class ProductManagerComponent {
  private readonly products = inject(ProductResource);

  protected readonly productsState = this.products.query().orderBy('name').paginateSignal(1, 5);

  protected readonly formOpen = signal(false);
  protected readonly editingId = signal<number | null>(null);
  protected readonly saving = signal(false);
  protected form: Partial<Product> = this.emptyForm();

  private emptyForm(): Partial<Product> {
    return { name: '', category: 'Electronics', price: 0, stock: 0, featured: false };
  }

  startCreate(): void {
    this.editingId.set(null);
    this.form = this.emptyForm();
    this.formOpen.set(true);
  }

  startEdit(product: Product): void {
    this.editingId.set(product.id);
    this.form = {
      name: product.name,
      category: product.category,
      price: product.price,
      stock: product.stock,
      featured: product.featured,
    };
    this.formOpen.set(true);
  }

  cancel(): void {
    this.formOpen.set(false);
  }

  save(): void {
    const id = this.editingId();
    this.saving.set(true);
    const request =
      id === null ? this.products.create(this.form) : this.products.update(id, this.form);
    request.subscribe({
      next: () => {
        this.saving.set(false);
        this.formOpen.set(false);
        this.productsState.refresh();
      },
      error: () => this.saving.set(false),
    });
  }

  toggleFeatured(product: Product): void {
    this.products
      .patch(product.id, { featured: !product.featured })
      .subscribe(() => this.productsState.refresh());
  }

  remove(id: number): void {
    this.products.destroy(id).subscribe(() => this.productsState.refresh());
  }

  setPage(page: number): void {
    if (page < 1) return;
    this.productsState.setPage(page);
  }
}`,
      },
      {
        name: 'product-manager.component.html',
        path: 'examples/product-manager.component.html',
        code: `<div class="manager">
  <header class="manager__header">
    <div>
      <h3>Products</h3>
      <p class="manager__hint">
        Live example — <code>ProductResource</code> extends
        <code>NgQlResource&lt;Product&gt;</code>.
      </p>
    </div>
    <button type="button" class="btn btn--primary" (click)="startCreate()">+ New product</button>
  </header>

  @if (formOpen()) {
    <form class="manager__form" (ngSubmit)="save()">
      <label>
        Name
        <input
          name="name"
          type="text"
          [ngModel]="form.name"
          (ngModelChange)="form.name = $event"
          required
        />
      </label>
      <label>
        Category
        <input
          name="category"
          type="text"
          [ngModel]="form.category"
          (ngModelChange)="form.category = $event"
        />
      </label>
      <label>
        Price
        <input
          name="price"
          type="number"
          step="0.01"
          [ngModel]="form.price"
          (ngModelChange)="form.price = $event"
        />
      </label>
      <label>
        Stock
        <input
          name="stock"
          type="number"
          [ngModel]="form.stock"
          (ngModelChange)="form.stock = $event"
        />
      </label>
      <label class="manager__checkbox">
        <input
          name="featured"
          type="checkbox"
          [ngModel]="form.featured"
          (ngModelChange)="form.featured = $event"
        />
        Featured
      </label>
      <div class="manager__form-actions">
        <button type="submit" class="btn btn--primary" [disabled]="saving()">
          {{ editingId() === null ? 'Create product' : 'Save changes' }}
        </button>
        <button type="button" class="btn btn--ghost" (click)="cancel()">Cancel</button>
      </div>
    </form>
  }

  @if (productsState.error()) {
    <div class="error-banner">Something went wrong loading products. Try again.</div>
  }

  @if (productsState.loading() && !productsState.hasData()) {
    <p class="hint">Loading products…</p>
  } @else if (productsState.hasData() && productsState.data()!.length === 0) {
    <p class="hint hint--empty">No products yet — create one above.</p>
  } @else if (productsState.hasData()) {
    <ul class="product-grid">
      @for (product of productsState.data(); track product.id) {
        <li class="product-card">
          @if (product.featured) {
            <span class="product-card__badge">★ Featured</span>
          }
          <span class="product-card__name">{{ product.name }}</span>
          <span class="product-card__category">{{ product.category }}</span>
          <span class="product-card__price">{{ product.price | currency }}</span>
          <span class="product-card__stock">{{ product.stock }} in stock</span>
          <div class="product-card__actions">
            <button type="button" class="btn btn--ghost" (click)="toggleFeatured(product)">
              {{ product.featured ? 'Unfeature' : 'Feature' }}
            </button>
            <button type="button" class="btn btn--ghost" (click)="startEdit(product)">Edit</button>
            <button type="button" class="btn btn--danger" (click)="remove(product.id)">
              Delete
            </button>
          </div>
        </li>
      }
    </ul>

    @if (productsState.meta(); as meta) {
      <div class="pagination-bar">
        <button
          type="button"
          class="btn"
          [disabled]="meta.currentPage <= 1"
          (click)="setPage(meta.currentPage - 1)"
        >
          ← Prev
        </button>
        <span>Page {{ meta.currentPage }} of {{ meta.lastPage }}</span>
        <button
          type="button"
          class="btn"
          [disabled]="meta.currentPage >= (meta.lastPage ?? 1)"
          (click)="setPage(meta.currentPage + 1)"
        >
          Next →
        </button>
      </div>
    }
  }
</div>`,
      },
    ],
  },
};
